### ISSUE TITLE
Direct communication with rflink?

### ISSUE THREAD

**Issue by adnanoner** [mlaurijsse/homebridge-rflink#1]
Looks cool 👍 . Does it directly communicate with an rflink connected on usb? You think it's easy to get it to work with motorized shades (Brel motors). I know that they are supported by rflink.
Are there any current gotcha's? Is everything working? (I could perhaps help out)

**Comment by mlaurijsse** [comment]
Yes, this plugin works with rifling over USB. I’ve tested on Mac OS X and Raspbian. Only issue encountered was that the user running homebridge (I run it as a service) should have read/write access to the serial port (e.g. added to the dailout group). I haven’t tested it on windows, but it is supported by the underlying packages, so I don’t expect any issues.

Motorized shades won’t work yet, only Switch, Lightbulb, StatelessProgrammableSwitch and StatefulProgrammableSwitch are currently implemented. But it’s straightforward to add this functionality for other HomeKit Services (See HAP-NodeJS project).

I won’t have time to do so in the coming weeks, but feel free to have a go at it yourself. I’d be glad to merge your changes.

**Comment by phis5533** [comment]
Hi @mlaurijsse & @adnanoner !

You mean connecting a RFLink enclosure (i.e https://www.nodo-shop.nl/en/rflink-gateway/130-rflink-enclosure.html#/7-behuizingen-transparant_arcyl) directly to the USB Mac will work with your plugin ?

My aim is to open/close a Gaposa motor with a QCT4S remote control to open or close my blinder.
This motor is supported by RFlink.

Thx for your help.
Regards.
Philippe
