### ISSUE TITLE
Log unknown devices

### ISSUE THREAD

**Issue by itavero** [mlaurijsse/homebridge-rflink#3]
After briefly looking at the code, it looks to me as if messages that are not matched to a device are simply ignored.
Personally I would think it would be nice if these would get logged (and possibly I had an ignore list, to ignore them in the future).
This would make it easier to add new devices and discover devices around you.

Logging could be done as all the other logging events, or perhaps use something like Telegram or e-mail (so I do not need to log on to the device, but get actively notified of "new" devices).

**Comment by mlaurijsse** [comment]
Hi Itavero,

I actually ignored those messages on purpose, to avoid clogging the log files. In my setup RFLink registers quite some gibberish, or just devices from my neighbors.  

You can enable extensive logging during development, by setting the `RFLINK_DEBUG` environment variable. You can do so by starting homebridge using 

`RFLINK_DEBUG=* ./bin/homebridge ....`

Please refer to the homebridge documentation for further reference.

Kind regards,

Marcel

**Comment by coolweb** [comment]
I think it should be possible to log unknow devices with a parameter, it’s not a development need but a user need. For example when you change the battery of oregon sensor the id change, when you buy a new device you don’t know the id. Could you add a switch in the settings?
