### ISSUE TITLE
Error: opening /dev/tty.usbmodemFD121

### ISSUE THREAD

**Issue by Bartruit** [mlaurijsse/homebridge-rflink#5]
I try to open this plugin in homebridge on a windows pc but i get this error (Unhandled rejection Error: Opening /dev/tty.usbmodemFD121": Unkown error code). I tried different ports but nothing works. Does anybody know's a solution? 

My Arduino Mega 2560 works on the folowing details according to usbdeview.exe.
Product ID: 0042
USB Class: 02
USB Protocol: 01
Drive letter: COM3
USB version: 1.10

I tried things like /dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyUSB2 /dev/ttyS0 /dev/ttyS1 /dev/ttyS2  /dev/tty.usbmodemFD121

**Comment by mlaurijsse** [comment]
Hi Bart,

Since you're on windows, should probably be COM3 (or other number). Please check node-serialport for further documentation on this part. 

I haven't tested this plugin in Windows environment. Node-serialport is supported in windows, so  I have high hopes it will.

Kind regards,

Marcel
